version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566" # Expose only ports for SQS (4566) and SNS (4575)
      - "4575:4575" # Expose only ports for SQS (4566) and SNS (4575)
      - "8055:8080" # Web UI
    environment:
      - SERVICES=sqs,sns
      - DEBUG=1
      - START_WEB=1
      - PORT_WEB_UI=8080

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db

  server:
    build: .
    ports:
      - "${PORT:-8080}:8000"
    volumes:
      - ./demo_app:/app/demo_app
      - ./saria:/app/saria
    working_dir: /app/demo_app
    command: poetry run uvicorn server.main:app --host 0.0.0.0 --reload --reload-dir=/app/demo_app --reload-dir=/app/saria
  consumer:
    build: .
    volumes:
      - ./demo_app:/app/demo_app
      - ./saria:/app/saria
    working_dir: /app/demo_app
    command: poetry run watchgod demo_app.consumer.main.run
